using System.Net.Sockets;
using System.Text;

namespace CodexApiSwitcher.Core;

internal sealed partial class SwitcherService
{
    private const string DefaultProxyHost = "127.0.0.1";
    private static readonly int[] CommonProxyPorts = [1082, 7890, 7897, 1080, 8080, 8888, 6152];

    internal ReconnectingRepairResult RepairReconnectingProxy()
    {
        var proxy = DetectLocalProxy();
        var endpoint = proxy.Endpoint;
        var primaryProxyUrl = proxy.HttpSupported ? "http://" + endpoint : "socks5h://" + endpoint;
        var allProxyUrl = proxy.Socks5Supported ? "socks5h://" + endpoint : primaryProxyUrl;
        var envPath = Path.Combine(root, ".env");
        var backupPath = string.Empty;
        var existed = File.Exists(envPath);
        if (existed)
        {
            Directory.CreateDirectory(backupDirectory);
            backupPath = Path.Combine(backupDirectory, ".env." + DateTime.Now.ToString("yyyyMMdd-HHmmss-fff") + ".bak");
            File.Copy(envPath, backupPath, false);
        }

        var lines = new[]
        {
            "# Codex proxy configuration",
            "# Generated by Codex API Switcher to repair frequent Reconnecting issues.",
            "# Local proxy detected on " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss") + ": " + endpoint + " (" + proxy.ProtocolDescription + ")",
            "HTTP_PROXY=" + primaryProxyUrl,
            "HTTPS_PROXY=" + primaryProxyUrl,
            "ALL_PROXY=" + allProxyUrl,
            "http_proxy=" + primaryProxyUrl,
            "https_proxy=" + primaryProxyUrl,
            "all_proxy=" + allProxyUrl,
            "NO_PROXY=localhost,127.0.0.1,::1",
            "no_proxy=localhost,127.0.0.1,::1"
        };
        AtomicFile.WriteText(envPath, lines);
        TryRestrictOwnerAccess(envPath);
        return new ReconnectingRepairResult(envPath, primaryProxyUrl, allProxyUrl, existed, backupPath, true, "支持协议：" + proxy.ProtocolDescription);
    }

    internal string DetectLocalProxyEndpoint() => DetectLocalProxy().Endpoint;

    private static LocalProxyCandidate DetectLocalProxy()
    {
        var tried = new List<string>();
        foreach (var port in GetConfiguredProxyPorts().Concat(CommonProxyPorts).Distinct())
        {
            var candidate = ProbeProxyPort(port);
            if (candidate.IsUsable) return candidate;
            tried.Add(port + "(" + candidate.ProbeMessage + ")");
        }

        throw new InvalidOperationException("未检测到可用的本地代理端口。请先打开代理客户端，再重试。已检查：" + string.Join("、", tried));
    }

    private static IEnumerable<int> GetConfiguredProxyPorts()
    {
        var keys = new[] { "HTTPS_PROXY", "HTTP_PROXY", "ALL_PROXY", "https_proxy", "http_proxy", "all_proxy" };
        foreach (var key in keys)
        {
            var value = Environment.GetEnvironmentVariable(key);
            if (TryGetLocalProxyPort(value, out var port)) yield return port;
        }
    }

    private static bool TryGetLocalProxyPort(string? value, out int port)
    {
        port = 0;
        if (string.IsNullOrWhiteSpace(value)) return false;
        var clean = value.Trim();
        if (!clean.Contains("://", StringComparison.Ordinal)) clean = "http://" + clean;
        if (!Uri.TryCreate(clean, UriKind.Absolute, out var uri)) return false;
        if (!IsLocalProxyHost(uri.Host) || uri.Port <= 0) return false;
        port = uri.Port;
        return true;
    }

    private static bool IsLocalProxyHost(string host) =>
        host.Equals("127.0.0.1", StringComparison.OrdinalIgnoreCase) ||
        host.Equals("localhost", StringComparison.OrdinalIgnoreCase) ||
        host.Equals("::1", StringComparison.OrdinalIgnoreCase) ||
        host.Equals("[::1]", StringComparison.OrdinalIgnoreCase);

    private static LocalProxyCandidate ProbeProxyPort(int port)
    {
        var socks = ProbeSocks5(port, TimeSpan.FromMilliseconds(900));
        var http = ProbeHttpProxy(port, TimeSpan.FromMilliseconds(1200));
        return new LocalProxyCandidate(port, http.Success, socks.Success, string.Join("; ", new[] { "HTTP " + http.Message, "SOCKS5 " + socks.Message }));
    }

    private static (bool Success, string Message) ProbeSocks5(int port, TimeSpan timeout)
    {
        try
        {
            using var client = ConnectTcp(DefaultProxyHost, port, timeout);
            client.ReceiveTimeout = (int)timeout.TotalMilliseconds;
            client.SendTimeout = (int)timeout.TotalMilliseconds;
            using var stream = client.GetStream();
            stream.Write(new byte[] { 0x05, 0x01, 0x00 });
            var response = new byte[2];
            var read = stream.Read(response, 0, response.Length);
            if (read >= 2 && response[0] == 0x05 && response[1] != 0xFF) return (true, "OK");
            return (false, "握手不匹配");
        }
        catch (Exception ex)
        {
            return (false, ex.Message);
        }
    }

    private static (bool Success, string Message) ProbeHttpProxy(int port, TimeSpan timeout)
    {
        try
        {
            using var client = ConnectTcp(DefaultProxyHost, port, timeout);
            client.ReceiveTimeout = (int)timeout.TotalMilliseconds;
            client.SendTimeout = (int)timeout.TotalMilliseconds;
            using var stream = client.GetStream();
            var request = Encoding.ASCII.GetBytes("CONNECT example.com:443 HTTP/1.1\r\nHost: example.com:443\r\nProxy-Connection: close\r\n\r\n");
            stream.Write(request, 0, request.Length);
            var buffer = new byte[64];
            var read = stream.Read(buffer, 0, buffer.Length);
            if (read <= 0) return (false, "无响应");
            var firstLine = Encoding.ASCII.GetString(buffer, 0, read).Split('\n')[0].Trim();
            if (!firstLine.StartsWith("HTTP/", StringComparison.OrdinalIgnoreCase)) return (false, "响应不是 HTTP");
            var parts = firstLine.Split(' ', StringSplitOptions.RemoveEmptyEntries);
            if (parts.Length >= 2 && int.TryParse(parts[1], out var statusCode))
            {
                if (statusCode is 200 or 403 or 407 or 502 or 503 or 504) return (true, statusCode.ToString());
                return (false, "HTTP " + statusCode);
            }
            return (true, firstLine);
        }
        catch (Exception ex)
        {
            return (false, ex.Message);
        }
    }

    private static TcpClient ConnectTcp(string host, int port, TimeSpan timeout)
    {
        var client = new TcpClient();
        try
        {
            var task = client.ConnectAsync(host, port);
            if (!task.Wait(timeout)) throw new TimeoutException("连接超时");
            if (!client.Connected) throw new IOException("连接失败");
            return client;
        }
        catch
        {
            client.Dispose();
            throw;
        }
    }

    private static void TryRestrictOwnerAccess(string path)
    {
        try
        {
            if (OperatingSystem.IsWindows()) return;
            File.SetUnixFileMode(path, UnixFileMode.UserRead | UnixFileMode.UserWrite);
        }
        catch { }
    }

    private sealed record LocalProxyCandidate(int Port, bool HttpSupported, bool Socks5Supported, string ProbeMessage)
    {
        internal bool IsUsable => HttpSupported || Socks5Supported;
        internal string Endpoint => DefaultProxyHost + ":" + Port;
        internal string ProtocolDescription => (HttpSupported, Socks5Supported) switch
        {
            (true, true) => "HTTP + SOCKS5",
            (true, false) => "HTTP",
            (false, true) => "SOCKS5",
            _ => "不可用"
        };
    }
}
